#!/bin/bash
# Author < HangsiaHONG hangsia@koompi.org >

CWD=$PWD
source $CWD/config

create_part() {
    sudo parted --script /dev/sdb \
	mklabel gpt \
	mkpart primary ext2 1Mib 101Mib \
	mkpart primary ext4 101Mib 5G \
	mkpart prmary ext4 5G 20G
}

format_part() {
    mkfs -v -t ext2 /dev/sdb1
	mkswap /dev/sdb2
	mkfs -v -t ext4 /dev/sdb3
}

mount_part() {
    mkdir -pv $KFS
	mount /dev/sdb3 $KFS
	/sbin/swapon -v /dev/sdb2
}

fetch_src() {
    mkdir -v $KFS/sources
	chmod -v a+wt $KFS/sources
	mv wget-list $KFS/sources
	cd $KFS/sources
	#wget http://www.linuxfromscratch.org/lfs/view/stable/wget-list
	wget --input-file=wget-list --continue --directory-prefix=$KFS/sources
}

create_layout() {
mkdir -pv $KFS/{bin,etc,lib,sbin,usr,var}
case $(uname -m) in
  x86_64) mkdir -pv $KFS/lib64 ;;
esac

mkdir -pv $KFS/tools    
}

create_kfs() {
    /sbin/groupadd kfs
	/sbin/useradd -s /bin/bash -g kfs -m -k /dev/null kfs
	passwd kfs

chown -v kfs $KFS/{usr,lib,var,etc,bin,sbin,tools}
case $(uname -m) in
  x86_64) chown -v kfs $KFS/lib64 ;;
esac

chown -v kfs $KFS/sources
}

main() {
    create_part &&
    format_part &&
    mount_part &&
    fetch_src &&
    create_layout &&
    create_kfs
}

main