#!/bin/bash
# Author < HangsiaHONG hangsia@koompi.org >
# Run this script as root user


CWD=$PWD
#source $CWD/config
KFS=/mnt/kfs

export KFS

7.2_change_ownership() {
chown -R root:root $KFS/{usr,lib,var,etc,bin,sbin,tools}
case $(uname -m) in
  x86_64) chown -R root:root $KFS/lib64 ;;
esac
}

7.3_prepare_virtual_kernel_file_systems() {
    mkdir -pv $KFS/{dev,proc,sys,run}

    # 7.3.1 Creating Initial Device Nodes
    mknod -m 600 $KFS/dev/console c 5 1
    mknod -m 666 $KFS/dev/null c 1 3

    # 7.3.2 Mounting and Populating /dev
    mount -v --bind /dev $KFS/dev

    # 7.3.3 Mounting Virtual Kernel File Systems
    mount -v --bind /dev/pts $KFS/dev/pts
    mount -vt proc proc $KFS/proc
    mount -vt sysfs sysfs $KFS/sys
    mount -vt tmpfs tmpfs $KFS/run

if [ -h $KFS/dev/shm ]; then
  mkdir -pv $KFS/$(readlink $KFS/dev/shm)
fi
}

7.4_enter_chroot() {
chroot "$KFS" /usr/bin/env -i   \
    HOME=/root                  \
    TERM="$TERM"                \
    PS1='(kfs chroot) \u:\w\$ ' \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin \
    /bin/bash --login +h    
}
main(){
    7.2_change_ownership && 7.3_prepare_virtual_kernel_file_systems && 7.4_enter_chroot
}

#main
chroot "$KFS" /usr/bin/env -i   \
    HOME=/root                  \
    TERM="$TERM"                \
    PS1='(kfs chroot) \u:\w\$ ' \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin \
    /bin/bash --login +h